# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quadratic.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'quadratic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\"3\n\x10QuadraticRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\t\n\x01\x63\x18\x03 \x01(\x05\"$\n\x11QuadraticResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\x10QuadraticService\x12\x39\n\x0eSolveQuadratic\x12\x11.QuadraticRequest\x1a\x12.QuadraticResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUADRATICREQUEST']._serialized_start=19
  _globals['_QUADRATICREQUEST']._serialized_end=70
  _globals['_QUADRATICRESPONSE']._serialized_start=72
  _globals['_QUADRATICRESPONSE']._serialized_end=108
  _globals['_QUADRATICSERVICE']._serialized_start=110
  _globals['_QUADRATICSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
